[package]
name = "pm-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
hdf5 = "0.8"
ndarray = "0.15"
pretty_assertions = "1.2"
